apiVersion: v1
kind: Service
metadata:
  name: sonarscanner
spec:
  type: LoadBalancer
  loadBalancerIP: 34.168.169.84
  ports:
    - port:  9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarscanner
